use_frameworks!


target 'Example (iOS)' do
  platform :ios, '9.0'
  pod 'Wormhole', :path => '../'
end

target 'Example (macOS)' do
  platform :osx, '10.10'
  pod 'Wormhole', :path => '../'
end

target 'Example (watchOS Extension)' do
  platform :watchos, '2.0'
  pod 'Wormhole', :path => '../'
end